### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hansputera** [hansputera/eraporsma-wrapper#1]
## AdminDashboard TODOs
- [ ] (AdminDashboard): Add "Grafik Nilai Siswa (Per Siswa/Per Mapel)" scraper
- [ ] (AdminDashboard): Add "Rekap Kehadiran Siswa" scraper
- [ ] (AdminDashboard): Add Dapodik's data synchronization feature
- [ ] (AdminDashboard & GuruDashboard): Add "Cetak Leger/Rapor" scraper

## SiswaDashboard TODOs
- [ ] (SiswaDashboard): Add "Rekap Absensi" scraper
- [ ] (SiswaDashboard): Add "Nilai Akhir Semester" scraper
- [ ] (SiswaDashboard): Add personality data scraper
